# Instruct Travis to build PRs as well as merges to master.
# See https://stackoverflow.com/a/31882307/145400.
branches:
  only:
    - master

language: python

# Work around Travis' lack of Python support on OS X.
# https://github.com/travis-ci/travis-ci/issues/2312#issuecomment-289140791

# The Travis CI build matrix is meant for two dimensions, not more. That is, it
# is not doing the right combinatorics for us. Take care of the combinatorics
# manually:

matrix:
  include:
    # Linux tests with Travis' CPython.
    - os: linux
      python: 2.7
      env: GEVENT_VERSION="default"
    - os: linux
      python: 2.7
      env: GEVENT_VERSION="gevent==1.5"

    - os: linux
      python: 3.4
      env: GEVENT_VERSION="default"
    - os: linux
      python: 3.4
      env: GEVENT_VERSION="gevent==1.5"

    - os: linux
      python: 3.5
      env: GEVENT_VERSION="default"
    - os: linux
      python: 3.5
      env: GEVENT_VERSION="gevent==1.5"

    - os: linux
      python: 3.6
      env: GEVENT_VERSION="default"
    - os: linux
      python: 3.6
      env: GEVENT_VERSION="gevent==1.5"

    # For supporting CPython 3.7 gevent >=1.3.x is required.
    # Test default (currently 20.6.x) and with 1.5.0.
    - os: linux
      dist: xenial
      python: 3.7
      env: GEVENT_VERSION="default"
    - os: linux
      dist: xenial
      python: 3.7
      env: GEVENT_VERSION="gevent==1.5"

    # For supporting CPython 3.8 gevent >=1.5.x is required.
    - os: linux
      dist: xenial
      python: 3.8
      env: GEVENT_VERSION="gevent==1.5"

    # Linux tests with Travis' PyPy. Test default gevent (currently 20.6.x) and
    # gevent 1.5.0.
    - os: linux
      python: pypy
      env: GEVENT_VERSION="default"
    - os: linux
      python: pypy
      env: GEVENT_VERSION="gevent==1.5"

    - os: linux
      python: pypy3
      env: GEVENT_VERSION="default"
    - os: linux
      python: pypy3
      env: GEVENT_VERSION="gevent==1.5"

    # Linux, but pyenv Python/PyPy builds. Only test current gevent.
    - os: linux
      language: generic
      env:
        - GEVENT_VERSION="default"
        - PYENV_PYTHON_VERSION=pypy3.6-7.3.1
    - os: linux
      language: generic
      env:
        - GEVENT_VERSION="default"
        - PYENV_PYTHON_VERSION=pypy2.7-7.3.1

    # Darwin tests. Test primarily with pyenv Python builds.
    # - os: osx
    #   language: generic
    #   env:
    #    - PYENV_PYTHON_VERSION=3.8.3
    #    - GEVENT_VERSION="gevent==1.5"
    - os: osx
      language: generic
      env:
        - PYENV_PYTHON_VERSION=3.7.9
        - GEVENT_VERSION="gevent==1.5.0"
    - os: osx
      language: generic
      env:
        - PYENV_PYTHON_VERSION=3.7.9
        - GEVENT_VERSION="gevent==1.4.0"
    - os: osx
      language: generic
      env:
        - PYENV_PYTHON_VERSION=3.6.10
        - GEVENT_VERSION="gevent==1.4.0"
    - os: osx
      language: generic
      env:
        - PYENV_PYTHON_VERSION=2.7.17
        - GEVENT_VERSION="gevent==1.4.0"
    - os: osx
      language: generic
      env:
        - PYENV_PYTHON_VERSION=pypy3.6-7.3.1
        - GEVENT_VERSION="gevent==1.4.0"
    # Test with system Python.
    - os: osx
      language: generic
      env:
        - GEVENT_VERSION="gevent==1.5.0"

install:
  - source ./ci/prepare-ci-env.sh

script:
  - python --version && uname -a
  - pip list
  - pytest -vv test/
  - bash examples/run-all.sh
  - bash ci/audit.sh
